### ISSUE TITLE
Error generating german umlaute

### ISSUE THREAD

**Issue by j-lang** [VirToReal/Hardy-Hershey-Text#2]
When entering german umlaute: äöüÄÖÜß the extension stops with the following error:
```Traceback (most recent call last):
  File "hardyhershey.py", line 504, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "hardyhershey.py", line 470, in effect
    w = make_string(self.options.text, font, spacing, spacing1, spacing2, g)
  File "hardyhershey.py", line 63, in make_string
    letterVals = [ord(q) - 32 for q in unicode(string,'utf-8')]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 8: unexpected end of data
```
running inkscape .92.2

**Comment by VirToReal** [comment]
just the "standard" font supports german umlaute. Should make some error exception for that some day ^^

**Comment by j-lang** [comment]
Thank you for advice.
But the error can be solved by changing line 63 to:
`	letterVals = [ord(q) - 32 for q in string]`
in 0.92.2

**Comment by VirToReal** [comment]
yeah, but then you won't be able to write german umlaute again ^^. Someday I will figure something out...  but thanks for you're support!

**Comment by j-lang** [comment]
Umlaute are there with standard font, all other fonts are throwing mapping error when there is an umlaut in string.

**Comment by VirToReal** [comment]
I know, but if you just change the line, you won't be able to place "äöüÄÖÜß" again. Because string just uses the ASCII Range of letters if not declared otherwise. Fixed that error with just checking which font you selected ;-)

Thanks for your help
